namespace SdevEng.Tests;

public class GitSafetyTests
{
    [Fact] public void OwnershipMarkersHaveDistinctGitPrivateLocationsAndVersionedWorktreeContents() { Assert.Equal("branch.factory/task-1.sdeveng-owned", "branch.factory/task-1." + GitOwnershipMarkers.BranchConfigKey); Assert.Equal("true", GitOwnershipMarkers.BranchConfigValue); Assert.Equal("sdeveng-owned-worktree", GitOwnershipMarkers.WorktreeFileName); Assert.Equal("sdeveng-owned-worktree-v1\n", GitOwnershipMarkers.WorktreeFileContents); }
    private static string PathsFile(params string[] paths) { var file = Path.Combine(Path.GetTempPath(), "owned-paths-" + Guid.NewGuid().ToString("N") + ".json"); File.WriteAllText(file, System.Text.Json.JsonSerializer.Serialize(paths)); return file; }
    private static Task<Result> RunGit(TemporaryGitRepository repo, string[] args) { var command = Cli.Parse(args); return new AgentTool.GitCommandModule().Execute(command, "", repo.Root, new Settings(new(), new(), new(), new()), CancellationToken.None); }
    [Fact] public async Task StageOwnedRejectsDirtyUnrelatedWorkspaceAndPreservesIt() { using var repo = new TemporaryGitRepository(); repo.Write("owned.txt", "owned"); repo.Write("user.txt", "unstaged"); var paths = PathsFile("owned.txt"); try { await Assert.ThrowsAsync<InvalidOperationException>(() => RunGit(repo, ["git", "stage-owned", "--paths-file", paths])); Assert.Empty((await Git.ChangedPaths(repo.Root, staged: true)).Paths); Assert.Equal("unstaged", File.ReadAllText(Path.Combine(repo.Root, "user.txt"))); } finally { File.Delete(paths); } }
    [Fact] public async Task StageOwnedStagesCleanOwnedScope() { using var repo = new TemporaryGitRepository(); repo.Write("owned.txt", "owned"); var paths = PathsFile("owned.txt"); try { var result = await RunGit(repo, ["git", "stage-owned", "--paths-file", paths]); Assert.Equal("ok", result.Status); Assert.Equal(new[] { "owned.txt" }, (await Git.ChangedPaths(repo.Root, staged: true)).Paths); } finally { File.Delete(paths); } }
    [Theory][InlineData("../outside.txt")][InlineData(".git/config")][InlineData("/tmp/outside.txt")] public async Task StageOwnedRejectsUnsafePaths(string path) { using var repo = new TemporaryGitRepository(); var file = PathsFile(path); try { await Assert.ThrowsAsync<InvalidOperationException>(() => RunGit(repo, ["git", "stage-owned", "--paths-file", file])); Assert.Empty((await Git.ChangedPaths(repo.Root, staged: true)).Paths); } finally { File.Delete(file); } }
    [Fact] public async Task StageOwnedRejectsUnchangedPath() { using var repo = new TemporaryGitRepository(); var file = PathsFile(".gitignore"); try { await Assert.ThrowsAsync<InvalidOperationException>(() => RunGit(repo, ["git", "stage-owned", "--paths-file", file])); Assert.Empty((await Git.ChangedPaths(repo.Root, staged: true)).Paths); } finally { File.Delete(file); } }
    [Fact] public async Task CommitOwnedRefusesUnrelatedStagedPath() { using var repo = new TemporaryGitRepository(); var head = repo.Run("rev-parse", "HEAD").Trim(); repo.Write("owned.txt", "owned"); repo.Write("other.txt", "other"); repo.Run("add", "other.txt"); var file = PathsFile("owned.txt"); try { await Assert.ThrowsAsync<InvalidOperationException>(() => RunGit(repo, ["git", "commit-owned", "--paths-file", file, "--message", "focused"])); Assert.Equal(head, repo.Run("rev-parse", "HEAD").Trim()); Assert.Equal(new[] { "other.txt" }, (await Git.ChangedPaths(repo.Root, staged: true)).Paths); } finally { File.Delete(file); } }
    [Fact] public async Task CommitOwnedCreatesFocusedCommitThroughRegisteredRuntime() { using var repo = new TemporaryGitRepository(); repo.Write("owned.txt", "owned"); var file = PathsFile("owned.txt"); try { await RunGit(repo, ["git", "stage-owned", "--paths-file", file]); var result = await AgentTool.Execute(Cli.Parse(["git", "commit-owned", "--paths-file", file, "--message", "focused change"]), AgentTool.FindToolkit(), repo.Root, new(new(), new(), new(), new())); Assert.Equal("ok", result.Status); var data = System.Text.Json.JsonSerializer.SerializeToNode(result.Data, AgentTool.Json)!; Assert.Equal(1, data["count"]!.GetValue<int>()); Assert.Equal("owned.txt", data["paths"]![0]!.GetValue<string>()); Assert.Equal("focused change", repo.Run("log", "-1", "--format=%s").Trim()); Assert.Empty(await Git.Changed(repo.Root)); } finally { File.Delete(file); } }
    [Fact] public async Task CreatesOwnedLocalBranchThroughGitCommandModule() { using var repo = new TemporaryGitRepository(); var command = Cli.Parse(["git", "branch-create", "--branch", "factory/task-1"]); var module = new AgentTool.GitCommandModule(); Assert.True(module.CanHandle(command)); var result = await module.Execute(command, "", repo.Root, new Settings(new(), new(), new(), new()), CancellationToken.None); Assert.Equal("ok", result.Status); Assert.Equal("factory/task-1", (await Git.State(repo.Root)).Branch); }
    [Fact] public async Task CreatesOwnedWorktreeThroughGitCommandModule() { using var repo = new TemporaryGitRepository(); var path = Path.Combine(Path.GetTempPath(), "codex-toolkit-worktree-" + Guid.NewGuid().ToString("N")); var command = Cli.Parse(["git", "worktree-create", "--branch", "factory/task-2", "--path", path]); var module = new AgentTool.GitCommandModule(); try { Assert.True(module.CanHandle(command)); var result = await module.Execute(command, "", repo.Root, new Settings(new(), new(), new(), new()), CancellationToken.None); Assert.Equal("ok", result.Status); Assert.True(Directory.Exists(path)); Assert.Equal("factory/task-2", (await Git.State(path)).Branch); } finally { await Processes.Run("git", ["worktree", "remove", "--force", path], repo.Root); if (Directory.Exists(path)) Directory.Delete(path, true); } }
    [Fact] public async Task WorktreeCreationPreservesExistingPath() { using var repo = new TemporaryGitRepository(); var path = Path.Combine(Path.GetTempPath(), "codex-toolkit-worktree-" + Guid.NewGuid().ToString("N")); Directory.CreateDirectory(path); try { await Assert.ThrowsAsync<InvalidOperationException>(() => new AgentTool.GitCommandModule().Execute(Cli.Parse(["git", "worktree-create", "--branch", "factory/task-3", "--path", path]), "", repo.Root, new Settings(new(), new(), new(), new()), CancellationToken.None)); Assert.Empty((await Git.Require(repo.Root, "branch", "--list", "factory/task-3")).Trim()); } finally { Directory.Delete(path, true); } }
    [Fact] public async Task PushOwnedPushesOnlyNamedBranchToLocalBareRemote() { using var repo = new TemporaryGitRepository(); var bare = Path.Combine(Path.GetTempPath(), "codex-toolkit-bare-" + Guid.NewGuid().ToString("N")); await Processes.Run("git", ["init", "--bare", bare], repo.Root); repo.Run("remote", "add", "local", bare); repo.Run("branch", "factory/push"); var head = repo.Run("rev-parse", "HEAD").Trim(); var command = Cli.Parse(["git", "push-owned", "--remote", "local", "--branch", "factory/push"]); var module = new AgentTool.GitCommandModule(); try { Assert.True(module.CanHandle(command)); var result = await AgentTool.Execute(command, AgentTool.FindToolkit(), repo.Root, new(new(), new(), new(), new())); Assert.Equal("ok", result.Status); var data = System.Text.Json.JsonSerializer.SerializeToNode(result.Data, AgentTool.Json)!; Assert.Equal("local", data["remote"]!.GetValue<string>()); Assert.Equal("factory/push", data["branch"]!.GetValue<string>()); Assert.Equal(head, data["head"]!.GetValue<string>()); Assert.Equal(head, (await Processes.Run("git", ["--git-dir", bare, "rev-parse", "refs/heads/factory/push"], repo.Root)).Output.Trim()); Assert.DoesNotContain("refs/heads/main", (await Processes.Run("git", ["--git-dir", bare, "show-ref", "--heads"], repo.Root)).Output); } finally { if (OperatingSystem.IsWindows()) foreach (var path in Directory.EnumerateFileSystemEntries(bare, "*", SearchOption.AllDirectories)) File.SetAttributes(path, FileAttributes.Normal); Directory.Delete(bare, true); } }
    [Fact] public async Task PushOwnedRejectsMissingBranchWithoutChangingRemote() { using var repo = new TemporaryGitRepository(); var bare = Path.Combine(Path.GetTempPath(), "codex-toolkit-bare-" + Guid.NewGuid().ToString("N")); await Processes.Run("git", ["init", "--bare", bare], repo.Root); repo.Run("remote", "add", "local", bare); try { await Assert.ThrowsAsync<InvalidOperationException>(() => RunGit(repo, ["git", "push-owned", "--remote", "local", "--branch", "absent"])); Assert.DoesNotContain("refs/heads/", (await Processes.Run("git", ["--git-dir", bare, "for-each-ref", "--format=%(refname)"], repo.Root)).Output); } finally { Directory.Delete(bare, true); } }
    [Fact] public async Task FailedPushReturnsRecoveryStateAndPreservesLocalBranch() { using var repo = new TemporaryGitRepository(); var bare = Path.Combine(Path.GetTempPath(), "codex-toolkit-bare-" + Guid.NewGuid().ToString("N")); await Processes.Run("git", ["init", "--bare", bare], repo.Root); repo.Run("remote", "add", "local", bare); repo.Run("branch", "factory/retry"); var head = repo.Run("rev-parse", "HEAD").Trim(); File.WriteAllText(Path.Combine(bare, "hooks", "pre-receive"), "#!/bin/sh\nexit 1\n"); if (!OperatingSystem.IsWindows()) File.SetUnixFileMode(Path.Combine(bare, "hooks", "pre-receive"), UnixFileMode.UserRead | UnixFileMode.UserWrite | UnixFileMode.UserExecute); try { var result = await AgentTool.Execute(Cli.Parse(["git", "push-owned", "--remote", "local", "--branch", "factory/retry"]), AgentTool.FindToolkit(), repo.Root, new(new(), new(), new(), new())); Assert.Equal("failed", result.Status); Assert.Equal(1, result.ExitCode); var data = System.Text.Json.JsonSerializer.SerializeToNode(result.Data, AgentTool.Json)!; Assert.Equal(head, data["head"]!.GetValue<string>()); Assert.Equal("local", data["remote"]!.GetValue<string>()); Assert.Equal("factory/retry", data["branch"]!.GetValue<string>()); Assert.NotEmpty(data["recovery"]!.GetValue<string>()); Assert.Equal(head, repo.Run("rev-parse", "refs/heads/factory/retry").Trim()); Assert.Empty((await Processes.Run("git", ["--git-dir", bare, "for-each-ref", "--format=%(refname)"], repo.Root)).Output.Trim()); } finally { Directory.Delete(bare, true); } }
    [Fact] public async Task WorktreeRemoveOwnedRemovesOnlyCleanLinkedWorktree() { using var repo = new TemporaryGitRepository(); var path = Path.Combine(Path.GetTempPath(), "codex-toolkit-worktree-" + Guid.NewGuid().ToString("N")); repo.Run("worktree", "add", "-b", "factory/remove", path); try { var command = Cli.Parse(["git", "worktree-remove-owned", "--path", path]); Assert.True(new AgentTool.GitCommandModule().CanHandle(command)); var result = await AgentTool.Execute(command, AgentTool.FindToolkit(), repo.Root, new(new(), new(), new(), new())); Assert.Equal("ok", result.Status); Assert.False(Directory.Exists(path)); Assert.DoesNotContain("worktree " + path, await Git.Require(repo.Root, "worktree", "list", "--porcelain")); } finally { if (Directory.Exists(path)) await Processes.Run("git", ["worktree", "remove", "--force", path], repo.Root); } }
    [Fact] public async Task WorktreeRemoveOwnedPreservesDirtyAndUnrecognizedPaths() { using var repo = new TemporaryGitRepository(); var path = Path.Combine(Path.GetTempPath(), "codex-toolkit-worktree-" + Guid.NewGuid().ToString("N")); repo.Run("worktree", "add", "-b", "factory/dirty", path); File.WriteAllText(Path.Combine(path, "keep.txt"), "keep"); var foreign = Path.Combine(Path.GetTempPath(), "codex-toolkit-foreign-" + Guid.NewGuid().ToString("N")); Directory.CreateDirectory(foreign); File.WriteAllText(Path.Combine(foreign, "keep.txt"), "foreign"); try { await Assert.ThrowsAsync<InvalidOperationException>(() => RunGit(repo, ["git", "worktree-remove-owned", "--path", path])); Assert.Equal("keep", File.ReadAllText(Path.Combine(path, "keep.txt"))); await Assert.ThrowsAsync<InvalidOperationException>(() => RunGit(repo, ["git", "worktree-remove-owned", "--path", foreign])); Assert.Equal("foreign", File.ReadAllText(Path.Combine(foreign, "keep.txt"))); } finally { await Processes.Run("git", ["worktree", "remove", "--force", path], repo.Root); Directory.Delete(foreign, true); } }
    [Fact] public async Task DirtyWorkIsPreserved() { using var repo = new TemporaryGitRepository(); repo.Write("user.txt", "keep"); await Assert.ThrowsAsync<InvalidOperationException>(() => Git.EnsureSafe(repo.Root, true)); Assert.Equal("keep", File.ReadAllText(Path.Combine(repo.Root, "user.txt"))); }
    [Fact] public async Task ReadsCleanDirtyAndUpstreamTrackingState() { using var repo = new TemporaryGitRepository(); Assert.True((await Git.State(repo.Root)).Clean); repo.Write("dirty.txt", "keep"); Assert.False((await Git.State(repo.Root)).Clean); repo.Run("remote", "add", "origin", "https://example.test/org/repo.git"); repo.Run("update-ref", "refs/remotes/origin/main", "HEAD"); repo.Run("branch", "--set-upstream-to=origin/main"); repo.Write("ahead.txt", "local"); repo.Commit(); var summary = System.Text.Json.JsonSerializer.SerializeToNode(await Repository.Summary(repo.Root, null, new()), AgentTool.Json)!; Assert.Equal("origin/main", summary["upstream"]!["name"]!.GetValue<string>()); Assert.Equal(1, summary["upstream"]!["ahead"]!.GetValue<int>()); Assert.Equal(0, summary["upstream"]!["behind"]!.GetValue<int>()); }
    [Fact] public async Task ReadsMergeBaseAndTwoSidedUpstreamDivergence() { using var repo = new TemporaryGitRepository(); var mergeBase = repo.Run("rev-parse", "HEAD").Trim(); repo.Run("remote", "add", "origin", "https://example.test/org/repo.git"); repo.Write("upstream.txt", "remote"); repo.Commit(); var upstream = repo.Run("rev-parse", "HEAD").Trim(); repo.Run("update-ref", "refs/remotes/origin/main", upstream); repo.Run("switch", "-c", "local", mergeBase); repo.Run("branch", "--set-upstream-to=origin/main"); repo.Write("local.txt", "local"); repo.Commit(); Assert.Equal(new[] { "local.txt" }, await Git.Changed(repo.Root, "origin/main")); var summary = System.Text.Json.JsonSerializer.SerializeToNode(await Repository.Summary(repo.Root, null, new()), AgentTool.Json)!; Assert.Equal(1, summary["upstream"]!["ahead"]!.GetValue<int>()); Assert.Equal(1, summary["upstream"]!["behind"]!.GetValue<int>()); }
    [Fact] public async Task StateReadsRepositoryRootAndStructuredRemoteIdentity() { using var repo = new TemporaryGitRepository(); repo.Run("remote", "add", "origin", "https://example.test/org/repo with space.git"); var state = await Git.State(repo.Root); Assert.Equal(repo.Root, state.Root); Assert.Contains(state.Remotes, remote => remote.name == "origin" && remote.url == "https://example.test/org/repo with space.git" && remote.direction == "(fetch)"); Assert.Contains(state.Remotes, remote => remote.name == "origin" && remote.url == "https://example.test/org/repo with space.git" && remote.direction == "(push)"); }
    [Fact] public async Task StatePreservesNewlinesInRemoteIdentity() { using var repo = new TemporaryGitRepository(); var url = "https://example.test/org/repo\nwith-newline.git"; repo.Run("remote", "add", "origin", url); var state = await Git.State(repo.Root); Assert.Contains(state.Remotes, remote => remote.name == "origin" && remote.url == url && remote.direction == "(fetch)"); Assert.Contains(state.Remotes, remote => remote.name == "origin" && remote.url == url && remote.direction == "(push)"); }
    [Theory]
    [InlineData("MERGE_HEAD")]
    [InlineData("CHERRY_PICK_HEAD")]
    [InlineData("REVERT_HEAD")]
    [InlineData("BISECT_LOG")]
    [InlineData("index.lock")]
    public async Task RefusesUnfinishedOperations(string marker) { using var repo = new TemporaryGitRepository(); File.WriteAllText(Path.Combine(repo.Root, ".git", marker), "fixture"); await Assert.ThrowsAsync<InvalidOperationException>(() => Git.EnsureSafe(repo.Root, false)); }
    [Fact] public async Task DetectsRebaseDirectory() { using var repo = new TemporaryGitRepository(); Directory.CreateDirectory(Path.Combine(repo.Root, ".git/rebase-merge")); Assert.Contains("rebase-merge", (await Git.State(repo.Root)).Operations); }
    [Fact] public async Task FindsStagedUnstagedUntrackedAndDeleted() { using var repo = new TemporaryGitRepository(); repo.Write("deleted.cs", "a"); repo.Write("space name.cs", "a"); repo.Commit(); File.Delete(Path.Combine(repo.Root, "deleted.cs")); repo.Write("space name.cs", "b"); repo.Write("new.cs", "a"); repo.Run("add", "new.cs"); repo.Write("untracked.cs", "a"); Assert.Equal(new[] { "deleted.cs", "new.cs", "space name.cs", "untracked.cs" }, await Git.Changed(repo.Root)); }
    [Fact] public async Task RenameReportsBothPaths() { using var repo = new TemporaryGitRepository(); repo.Write("old.cs", "same"); repo.Commit(); repo.Run("mv", "old.cs", "new.cs"); var files = await Git.Changed(repo.Root); Assert.Contains("old.cs", files); Assert.Contains("new.cs", files); }
    [Fact] public async Task BaseIncludesCommittedAndLocalChanges() { using var repo = new TemporaryGitRepository(); var baseline = repo.Run("rev-parse", "HEAD").Trim(); repo.Write("committed.cs", "x"); repo.Commit(); repo.Write("local.cs", "x"); Assert.Equal(new[] { "committed.cs", "local.cs" }, await Git.Changed(repo.Root, baseline)); }
    [Fact] public async Task LinkedWorktreeOperationIsDetected() { using var repo = new TemporaryGitRepository(); var linked = Path.Combine(repo.Root, "linked"); repo.Run("worktree", "add", "-b", "other", linked); var gitDir = (await Git.Require(linked, "rev-parse", "--absolute-git-dir")).Trim(); File.WriteAllText(Path.Combine(gitDir, "CHERRY_PICK_HEAD"), "fixture"); Assert.Contains("CHERRY_PICK_HEAD", (await Git.State(linked)).Operations); }
}
