<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsTestProject>true</IsTestProject>
    <OutputType>Library</OutputType>
    <IsPackable>false</IsPackable>
    <GenerateProgramFile>false</GenerateProgramFile>
    <EnableDefaultCompileItems>true</EnableDefaultCompileItems>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.ML.Tokenizers.Data.Cl100kBase" PrivateAssets="all" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="Microsoft.Extensions.Http" />
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" />
    <PackageReference Include="OpenTelemetry.Extensions.Hosting" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" PrivateAssets="all" />
    <PackageReference Include="YamlDotNet" PrivateAssets="all" />
    <PackageReference Include="Tomlyn" PrivateAssets="all" />
    <PackageReference Include="JsonSchema.Net" PrivateAssets="all" />
    <Using Include="Xunit" />
    <Using Include="SdevEng" />
    <ProjectReference Include="../../src/SdevEng.Core/SdevEng.Core.csproj" />
    <ProjectReference Include="../../src/SdevEng.Infrastructure/SdevEng.Infrastructure.csproj" />
    <ProjectReference Include="../../src/SdevEng.Cli/SdevEng.Cli.csproj" />
  </ItemGroup>
</Project>
